sudo: false
language: scala
jdk:
- oraclejdk8
scala:
- 2.12.10
- 2.13.1
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
  - $TRAVIS_BUILD_DIR/target
  - $TRAVIS_BUILD_DIR/project/target
script:
- sbt ++$TRAVIS_SCALA_VERSION "test"
- find $HOME/.sbt -name "*.lock" -exec rm {} \;
- find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} \;
