platform: linux

image_resource:
  type: docker-image
  source:
    repository: hseeberger/scala-sbt

inputs:
- name: play-json-cats

run:
  path: ./play-json-cats/build.sh

caches:
  - path: .ivy2/cache
  - path: .sbt/boot/
  - path: play-json-cats/target
  - path: play-json-cats/project/target

